// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6DVK4MB4m-RjqASc1KTl3joB2Kx2sWc',
    appId: '1:524302742919:web:ef0a71fd920f2b968c4f22',
    messagingSenderId: '524302742919',
    projectId: 'project-4-6875a',
    authDomain: 'project-4-6875a.firebaseapp.com',
    storageBucket: 'project-4-6875a.appspot.com',
    measurementId: 'G-LWWH5MXCSJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfJ0ag3w2xtmZAycFoW-LLRysJZUzdaYY',
    appId: '1:524302742919:ios:b8fd87fd71e743c58c4f22',
    messagingSenderId: '524302742919',
    projectId: 'project-4-6875a',
    storageBucket: 'project-4-6875a.appspot.com',
    iosClientId: '524302742919-csri5lem0pvulabs7t0vnvt8ukbidke2.apps.googleusercontent.com',
    iosBundleId: 'com.example.project4',
  );
}
